### ISSUE TITLE
Use springboot 2.7.0+ with SecurityFilterChain instead of deprecated WebSecurityConfigurerAdapter 

### ISSUE THREAD

**Issue by mmaccari** [kakawait/cas-security-spring-boot-starter#161]
When upgrading my applications to springboot 2.7.0 and using SecurityFilterChain  instead of deprecated WebSecurityConfigurerAdapter I get an error message.

`Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.IllegalStateException: Found WebSecurityConfigurerAdapter as well as SecurityFilterChain. Please select just one.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 21 common frames omitted
Caused by: java.lang.IllegalStateException: Found WebSecurityConfigurerAdapter as well as SecurityFilterChain. Please select just one.`

**Comment by kakawait** [comment]
I've started working on subject through https://github.com/kakawait/cas-security-spring-boot-starter/tree/support-spring-boot-2.7

Mostly working, but few breaking changes. Thus I've to do more documentations and migration path
